### ISSUE TITLE
Slideshow does not work with P3D

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gicentre/gicentreutils#8]
```
The Slideshow example provided with the library does not work correctly if P3D 
is used. A grey screen appears but nothing else. Sketches are still running in 
the background, but are not displayed in the main sketch window.
```

Original issue reported on code.google.com by `jwoLon...@gmail.com` on 7 Sep 2010 at 7:52

**Comment by jwoLondon** [comment]
Slideshow has been temporarily removed from V3.4 as it relied on AWT implementation details. Processing 3.x is now platform agnostic so if we re-introduce the multiSketch package we will need to use a new approach to embedding sketches inside other sketches.
